[package]
name = "kost_control_frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo-net = "0.6.0"
gloo-storage = "0.3.0"
serde = "1.0.228"
serde_json = "1.0.145"
wasm-bindgen-futures = "0.4.56"
web-sys = "0.3.83"
yew = { version = "0.22.0", features = ["csr"] }
yew-router = "0.19.0"
